
import java.awt.Color;
import java.awt.Container;
import java.awt.Image;
import java.sql.*;
import javax.swing.JLabel;
import javax.swing.JPanel;
public class Search extends javax.swing.JFrame {
    /**
     * Creates new form Search
     */
    static Search s=new Search();
    public Search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(338, 569));
        setResizable(false);

        top.setBackground(java.awt.Color.red);
        top.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(java.awt.Color.red);
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Back");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Type something..");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.red);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Go");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        result.setBackground(new java.awt.Color(255, 255, 255));
        result.setPreferredSize(new java.awt.Dimension(0, 100));

        javax.swing.GroupLayout resultLayout = new javax.swing.GroupLayout(result);
        result.setLayout(resultLayout);
        resultLayout.setHorizontalGroup(
            resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        resultLayout.setVerticalGroup(
            resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(result);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setForeground(Color.RED);
        jLabel1.setBackground(Color.white);
        
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setForeground(Color.white);
        jLabel1.setBackground(Color.RED);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        jLabel1.setForeground(Color.white);
        jLabel1.setBackground(Color.RED); 
        Home.home.setVisible(true);
         this.dispose();       
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       //sql part here and remove the label and the middle
       //if(!jTextField1.getText().equals("Type something..")){
           s.result.removeAll();

           String search = s.jTextField1.getText();
           Sql s = new Sql();
            //JLabel j[]= new JLabel[2000];
               int i=0;
           try{
               Statement st = s.fetchStatement();
               ResultSet count = (st.executeQuery("Select count(moviename) from movies where moviename like '%"+search+"%';"));
               count.next();
               int nos = count.getInt(1);
               if(nos == 0){
                   JLabel j = new JLabel();                  
                   Search.s.result.add(j);
                   j.setText("This wasn't part of the Script. We couldn't find anything :(");
                   j.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
                   j.setSize(325, 60);                      
                   j.setLocation(0, 90); 
//                   JLabel j2 = new JLabel();                  
//                   Search.s.result.add(j2);
//                   j2.setText("We couldn't find anything");
//                   j2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
                   //j2.setSize(298, 60);                      
                   //j2 .setLocation(0, 60); 
                   Search.s.repaint();
               }
               else{
                    //Search.s.result.removeAll();
                    String q = "Select moviename,movie_id from movies where moviename like '%"+search+"%';";
                    if(search.trim().equals(""))
                        q = "Select moviename,movie_id from movies order by moviename;";
                    ResultSet rs = st.executeQuery(q);
                    JPanel panel[] = new JPanel[nos];
                    JLabel j[] =  new JLabel[nos];
                    int y = 0;
                    while(rs.next()){                   
                        String x = rs.getString(1);
                        String id=  rs.getString(2);
                        //System.out.println(x);

                        j[i] = new JLabel();
                        j[i].setName(id);
                        Search.s.result.add(j[i]);
                        j[i].setText(x);
                        j[i].setSize(325, 60);                      
                        j[i].setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
                        j[i].addMouseListener(new java.awt.event.MouseAdapter() {
                             public void mouseClicked(java.awt.event.MouseEvent evt) {
                                 String id= ((JLabel)evt.getSource()).getName();
                                 String name = ((JLabel)evt.getSource()).getText();
                                 String dest = name+id;
                                 Show x = new Show();

                            if(dest.equals("The Lord of the Rings: The Return of the King15")){
                                dest = "The Lord of the Rings";
                            }
                            if(dest.equals("All the President's Men29")){
                                dest = "All the Presidents Men29";
                            }
                            x.jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/downloads/"+dest+".jpg")));
                                 x.jLabel1.setName(id);
                                 x.jLabel1.setText(name);
                                                                
                                 
                                        String actors  = "";
                                            String lang  = "";
                                            String genre  = "";
                                            String desc = "";
                                            String rdate  = "";
                                    Sql se = new Sql();
                                    try{
                                        Statement st = se.fetchStatement();
                                        String q = "Select * from movies where movie_id = '" + x.jLabel1.getName() +"'";
                                        ResultSet rs= st.executeQuery(q);
                                        while(rs.next()){
                                             actors  = rs.getString(4);
                                             lang  = rs.getString(3);
                                             genre  = rs.getString(7);
                                             desc = rs.getString(5);
                                             rdate  = rs.getString(6);
                                             //System.out.println(actors+" "+lang+ " "+rdate+"\n"+desc);
                                        }
                                    }
                                    catch(Exception e){
                                               System.out.println(e);
                                    }                      
                                 
                                 
                                            x.lang.setText("Language: "+lang);
                                            x.actors.setText("Actors: "+actors);
                                            x.genre.setText("Genre: "+genre);
                                            x.desc.setText(desc);
                                            x.rdate.setText("Release Date: "+rdate);
                                             x.setVisible(true);
                                 Search.s.setVisible(false); 
                                 
                             }
                         });
                        j[i].setVisible(true);
                        j[i].setLocation(0, y);                   
                        i++;
                        y+= 60;
                     }  
                     result.setPreferredSize(new java.awt.Dimension(0, y));
                }
           }
           catch(Exception e){
                System.out.println(e.getCause());
           }
     //  }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
         jLabel3.setForeground(Color.white);
        jLabel3.setBackground(Color.RED);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
       jLabel3.setForeground(Color.RED);
        jLabel3.setBackground(Color.white);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        if(jTextField1.getText().equals("Type something..")){
            jTextField1.setText("");
            jTextField1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextField1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                s.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JPanel result;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
